FROM python:3.11

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --upgrade pip
RUN pip3 install -r requirements.txt
COPY . .
RUN prisma generate && prisma migrate dev --name init

# CMD ["python", "app/interfaces/telegram_bot/bot.py"]
CMD ["sh", "-c", "prisma generate && prisma migrate dev --name init && python app/interfaces/telegram_bot/bot.py"]
